const option = (value, label = value) => ({ value, label });

const statusOptions = [
  option('Active', 'Đang hoạt động'),
  option('Inactive', 'Ngừng hoạt động'),
  option('Pending', 'Chờ duyệt'),
  option('Approved', 'Đã duyệt'),
  option('Rejected', 'Từ chối'),
  option('Cancelled', 'Đã hủy'),
  option('Completed', 'Hoàn tất'),
  option('Draft', 'Bản nháp'),
  option('Submitted', 'Đã gửi'),
  option('Running', 'Đang chạy'),
  option('Failed', 'Thất bại'),
];

export const managementConfigs = {
  departments: {
    endpoint: '/departments',
    idField: 'DepartmentID',
    eyebrow: 'UC.03',
    title: 'Phòng ban',
    description: 'Quản lý cơ cấu phòng ban trong hệ thống Payroll.',
    fields: [
      { name: 'DepartmentID', label: 'Mã phòng ban', type: 'number' },
      { name: 'DepartmentName', label: 'Tên phòng ban' },
      { name: 'SyncedAt', label: 'Thời điểm đồng bộ', readOnly: true },
    ],
  },
  positions: {
    endpoint: '/positions',
    idField: 'PositionID',
    eyebrow: 'UC.03',
    title: 'Chức vụ',
    description: 'Quản lý danh mục chức vụ và chức danh nhân sự.',
    fields: [
      { name: 'PositionID', label: 'Mã chức vụ', type: 'number' },
      { name: 'PositionName', label: 'Tên chức vụ' },
      { name: 'SyncedAt', label: 'Thời điểm đồng bộ', readOnly: true },
    ],
  },
  employeeLifecycle: {
    endpoint: '/employee-lifecycle',
    idField: 'LifecycleID',
    eyebrow: 'UC.02',
    title: 'Vòng đời nhân viên',
    description: 'Quản lý các sự kiện tuyển dụng, điều chuyển, nghỉ phép dài hạn, chấm dứt và tái tuyển dụng.',
    fields: [
      { name: 'LifecycleID', label: 'Mã sự kiện', readOnly: true },
      { name: 'EmployeeID', label: 'Mã nhân viên', type: 'number' },
      { name: 'EventType', label: 'Loại sự kiện', options: [option('Hired', 'Tuyển dụng'), option('Promoted', 'Thăng chức'), option('Transferred', 'Điều chuyển'), option('OnLeave', 'Nghỉ dài hạn'), option('Terminated', 'Chấm dứt'), option('Rehired', 'Tái tuyển dụng')], badge: true },
      { name: 'EventDate', label: 'Ngày hiệu lực', type: 'date' },
      { name: 'FromPosition', label: 'Chức vụ cũ', table: false },
      { name: 'ToPosition', label: 'Chức vụ mới' },
      { name: 'FromDept', label: 'Phòng ban cũ', table: false },
      { name: 'ToDept', label: 'Phòng ban mới' },
      { name: 'Notes', label: 'Ghi chú', table: false },
    ],
  },
  onboardingOffboarding: {
    endpoint: '/onboarding-offboarding',
    idField: 'RecordID',
    eyebrow: 'UC.04',
    title: 'Tiếp nhận / Nghỉ việc',
    description: 'Theo dõi quy trình onboarding/offboarding, người phụ trách, mốc thời gian và trạng thái hoàn tất.',
    fields: [
      { name: 'RecordID', label: 'Mã quy trình', readOnly: true },
      { name: 'EmployeeID', label: 'Mã nhân viên', type: 'number' },
      { name: 'ProcessType', label: 'Loại quy trình', options: [option('Onboarding', 'Tiếp nhận'), option('Offboarding', 'Nghỉ việc')], badge: true },
      { name: 'StartDate', label: 'Ngày bắt đầu', type: 'date' },
      { name: 'TargetDate', label: 'Ngày dự kiến', type: 'date' },
      { name: 'CompletedDate', label: 'Ngày hoàn tất', type: 'date', table: false },
      { name: 'Status', label: 'Trạng thái', options: statusOptions, badge: true },
      { name: 'AssignedTo', label: 'Người phụ trách', type: 'number', table: false },
      { name: 'Notes', label: 'Ghi chú', table: false },
    ],
  },
  workShifts: {
    endpoint: '/work-shifts',
    idField: 'ShiftID',
    eyebrow: 'UC.06',
    title: 'Ca làm việc',
    description: 'Thiết lập ca làm việc, thời gian nghỉ giữa ca, ca đêm và trạng thái sử dụng.',
    fields: [
      { name: 'ShiftID', label: 'Mã ca', readOnly: true },
      { name: 'ShiftName', label: 'Tên ca' },
      { name: 'StartTime', label: 'Giờ bắt đầu', type: 'time' },
      { name: 'EndTime', label: 'Giờ kết thúc', type: 'time' },
      { name: 'BreakMinutes', label: 'Nghỉ giữa ca', type: 'number', defaultValue: 60 },
      { name: 'IsNightShift', label: 'Ca đêm', type: 'number', defaultValue: 0 },
      { name: 'IsActive', label: 'Đang dùng', type: 'number', defaultValue: 1, badge: true },
      { name: 'Description', label: 'Mô tả', table: false },
    ],
  },
  shiftAssignments: {
    endpoint: '/shift-assignments',
    idField: 'AssignmentID',
    eyebrow: 'UC.06',
    title: 'Phân ca',
    description: 'Gán ca làm việc cho nhân viên theo ngày hiệu lực.',
    fields: [
      { name: 'AssignmentID', label: 'Mã phân ca', readOnly: true },
      { name: 'EmployeeID', label: 'Mã nhân viên', type: 'number' },
      { name: 'ShiftID', label: 'Mã ca', type: 'number' },
      { name: 'EffectiveDate', label: 'Ngày hiệu lực', type: 'date' },
      { name: 'EndDate', label: 'Ngày kết thúc', type: 'date' },
      { name: 'CreatedBy', label: 'Người tạo', type: 'number', table: false },
    ],
  },
  overtimeLeave: {
    endpoint: '/leave-requests',
    idField: 'LeaveID',
    eyebrow: 'UC.07',
    title: 'Nghỉ phép & Tăng ca',
    description: 'Quản lý đơn nghỉ phép; API tăng ca vẫn được giữ tại /overtime-requests cho phần mở rộng.',
    fields: [
      { name: 'LeaveID', label: 'Mã đơn', readOnly: true },
      { name: 'EmployeeID', label: 'Mã nhân viên', type: 'number' },
      { name: 'LeaveType', label: 'Loại nghỉ', options: [option('Annual', 'Nghỉ phép năm'), option('Sick', 'Nghỉ ốm'), option('Maternity', 'Thai sản'), option('Unpaid', 'Không lương'), option('Other', 'Khác')] },
      { name: 'StartDate', label: 'Từ ngày', type: 'date' },
      { name: 'EndDate', label: 'Đến ngày', type: 'date' },
      { name: 'TotalDays', label: 'Số ngày', type: 'number', defaultValue: 1 },
      { name: 'Status', label: 'Trạng thái', options: statusOptions, badge: true },
      { name: 'Reason', label: 'Lý do', table: false },
    ],
  },
  overtimeRequests: {
    endpoint: '/overtime-requests',
    idField: 'OvertimeID',
    eyebrow: 'UC.07',
    title: 'Đơn tăng ca',
    description: 'Theo dõi và phê duyệt giờ tăng ca phục vụ tổng hợp công và tính lương.',
    fields: [
      { name: 'OvertimeID', label: 'Mã đơn', readOnly: true },
      { name: 'EmployeeID', label: 'Mã nhân viên', type: 'number' },
      { name: 'OvertimeDate', label: 'Ngày tăng ca', type: 'date' },
      { name: 'StartTime', label: 'Giờ bắt đầu', type: 'time' },
      { name: 'EndTime', label: 'Giờ kết thúc', type: 'time' },
      { name: 'Hours', label: 'Số giờ', type: 'number' },
      { name: 'OvertimeType', label: 'Loại tăng ca', options: [option('Weekday', 'Ngày thường'), option('Weekend', 'Cuối tuần'), option('Holiday', 'Ngày lễ')] },
      { name: 'Status', label: 'Trạng thái', options: statusOptions, badge: true },
      { name: 'Reason', label: 'Lý do', table: false },
    ],
  },
  salaryPolicies: {
    endpoint: '/salary-policies',
    idField: 'PolicyID',
    eyebrow: 'UC.09',
    title: 'Chính sách lương',
    description: 'Quản lý khung lương, thuế, bảo hiểm và hệ số tăng ca.',
    fields: [
      { name: 'PolicyID', label: 'Mã chính sách', readOnly: true },
      { name: 'PolicyName', label: 'Tên chính sách' },
      { name: 'PolicyCode', label: 'Mã viết tắt' },
      { name: 'BaseSalaryMin', label: 'Lương tối thiểu', type: 'number', defaultValue: 0 },
      { name: 'BaseSalaryMax', label: 'Lương tối đa', type: 'number' },
      { name: 'OvertimeRate', label: 'Hệ số tăng ca', type: 'number', defaultValue: 1.5 },
      { name: 'TaxRate', label: 'Thuế (%)', type: 'number', defaultValue: 10 },
      { name: 'IsActive', label: 'Đang dùng', type: 'number', defaultValue: 1, badge: true },
    ],
  },
  benefitsInsurance: {
    endpoint: '/benefits-insurance',
    idField: 'BenefitID',
    eyebrow: 'UC.11',
    title: 'Phúc lợi & Bảo hiểm',
    description: 'Theo dõi gói phúc lợi, nhà cung cấp, chi phí và trạng thái hiệu lực.',
    fields: [
      { name: 'BenefitID', label: 'Mã phúc lợi', readOnly: true },
      { name: 'EmployeeID', label: 'Mã nhân viên', type: 'number' },
      { name: 'BenefitType', label: 'Loại phúc lợi' },
      { name: 'Provider', label: 'Nhà cung cấp' },
      { name: 'MonthlyCost', label: 'Chi phí tháng', type: 'number', defaultValue: 0 },
      { name: 'EmployerShare', label: 'Công ty trả', type: 'number', defaultValue: 0 },
      { name: 'EmployeeShare', label: 'Nhân viên trả', type: 'number', defaultValue: 0 },
      { name: 'Status', label: 'Trạng thái', options: statusOptions, badge: true },
    ],
  },
  payrollAdjustments: {
    endpoint: '/payroll-adjustments',
    idField: 'AdjustmentID',
    eyebrow: 'UC.12',
    title: 'Điều chỉnh lương',
    description: 'Ghi nhận thưởng, khấu trừ, phụ cấp và trạng thái phê duyệt.',
    fields: [
      { name: 'AdjustmentID', label: 'Mã điều chỉnh', readOnly: true },
      { name: 'EmployeeID', label: 'Mã nhân viên', type: 'number' },
      { name: 'SalaryMonth', label: 'Kỳ lương', type: 'date' },
      { name: 'AdjustType', label: 'Loại điều chỉnh', options: [option('Bonus', 'Thưởng'), option('Deduction', 'Khấu trừ'), option('Allowance', 'Phụ cấp'), option('Commission', 'Hoa hồng')] },
      { name: 'Amount', label: 'Số tiền', type: 'number' },
      { name: 'Status', label: 'Trạng thái', options: statusOptions, badge: true },
      { name: 'Reason', label: 'Lý do', table: false },
    ],
  },
  kpiOkr: {
    endpoint: '/kpi-okr',
    idField: 'KpiID',
    eyebrow: 'UC.13',
    title: 'KPI / OKR',
    description: 'Quản lý mục tiêu, chỉ số đo lường, trọng số và điểm đánh giá.',
    fields: [
      { name: 'KpiID', label: 'Mã KPI', readOnly: true },
      { name: 'EmployeeID', label: 'Mã nhân viên', type: 'number' },
      { name: 'Period', label: 'Chu kỳ' },
      { name: 'Title', label: 'Mục tiêu' },
      { name: 'TargetValue', label: 'Chỉ tiêu', type: 'number' },
      { name: 'ActualValue', label: 'Thực đạt', type: 'number' },
      { name: 'Weight', label: 'Trọng số (%)', type: 'number', defaultValue: 100 },
      { name: 'Score', label: 'Điểm', type: 'number' },
      { name: 'Status', label: 'Trạng thái', options: statusOptions, badge: true },
    ],
  },
  performanceEvaluation: {
    endpoint: '/performance-evaluation',
    idField: 'ReviewID',
    eyebrow: 'UC.14',
    title: 'Đánh giá hiệu suất',
    description: 'Lập phiếu đánh giá nhân viên, điểm tổng hợp, xếp loại và trạng thái duyệt.',
    fields: [
      { name: 'ReviewID', label: 'Mã đánh giá', readOnly: true },
      { name: 'EmployeeID', label: 'Mã nhân viên', type: 'number' },
      { name: 'ReviewPeriod', label: 'Kỳ đánh giá' },
      { name: 'ReviewDate', label: 'Ngày đánh giá', type: 'date' },
      { name: 'ReviewerID', label: 'Người đánh giá', type: 'number' },
      { name: 'OverallScore', label: 'Điểm tổng', type: 'number' },
      { name: 'Grade', label: 'Xếp loại' },
      { name: 'Status', label: 'Trạng thái', options: statusOptions, badge: true },
    ],
  },
  users: {
    endpoint: '/users',
    idField: 'UserID',
    eyebrow: 'UC.20',
    title: 'Người dùng',
    description: 'Quản lý tài khoản đăng nhập, vai trò RBAC và liên kết nhân viên.',
    fields: [
      { name: 'UserID', label: 'Mã người dùng', readOnly: true },
      { name: 'Username', label: 'Tên đăng nhập' },
      { name: 'Email', label: 'Email', type: 'email' },
      { name: 'PasswordHash', label: 'Mật khẩu', table: false, type: 'password', placeholder: 'Nhập mật khẩu mới' },
      { name: 'FullName', label: 'Họ tên' },
      { name: 'Role', label: 'Vai trò', options: [option('Admin', 'Quản trị'), option('HR_Manager', 'Quản lý nhân sự'), option('Payroll_Manager', 'Quản lý lương'), option('Employee', 'Nhân viên')], badge: true },
      { name: 'EmployeeID', label: 'Mã nhân viên', type: 'number' },
      { name: 'IsActive', label: 'Đang dùng', type: 'number', defaultValue: 1, badge: true },
    ],
  },
  systemBackup: {
    endpoint: '/system-backup',
    idField: 'BackupID',
    eyebrow: 'UC.23',
    title: 'Sao lưu & Bảo mật',
    description: 'Theo dõi lịch sử sao lưu thủ công/tự động và trạng thái bảo mật hệ thống.',
    fields: [
      { name: 'BackupID', label: 'Mã sao lưu', readOnly: true },
      { name: 'BackupType', label: 'Loại sao lưu', options: [option('Manual', 'Thủ công'), option('Scheduled', 'Theo lịch'), option('Auto', 'Tự động')] },
      { name: 'BackupName', label: 'Tên bản sao lưu' },
      { name: 'FilePath', label: 'Đường dẫn file', table: false },
      { name: 'FileSize', label: 'Dung lượng', type: 'number', table: false },
      { name: 'Status', label: 'Trạng thái', options: statusOptions, badge: true },
      { name: 'Duration', label: 'Thời lượng', type: 'number' },
      { name: 'Notes', label: 'Ghi chú', table: false },
    ],
  },
  auditLogs: {
    endpoint: '/audit-logs',
    idField: 'LogID',
    eyebrow: 'Audit',
    title: 'Nhật ký hệ thống',
    description: 'Tra cứu các thao tác quan trọng đã được backend ghi nhận.',
    readOnly: true,
    fields: [
      { name: 'LogID', label: 'Mã log', readOnly: true },
      { name: 'Username', label: 'Người dùng' },
      { name: 'Action', label: 'Hành động', badge: true },
      { name: 'EntityType', label: 'Đối tượng' },
      { name: 'EntityID', label: 'Mã đối tượng' },
      { name: 'IPAddress', label: 'IP', table: false },
      { name: 'CreatedAt', label: 'Thời điểm' },
    ],
  },
};
